import { AppData } from './types';
import { scrapedStaff } from './scraped-staff-data';

export const initialData: AppData = {
  programImages: {},
  staff: scrapedStaff,
  highlights: [
    {
      id: 'hl-tcas69',
      title: 'MFUTCAS69 — Undergraduate Admission Schedule 2026',
      titleTH: 'MFUTCAS69 — กำหนดการรับสมัครนักศึกษาใหม่ ระดับปริญญาตรี ปีการศึกษา 2569',
      description: 'MFU undergraduate admission schedule for academic year 2026 — Round 1 (Portfolio), Round 2 (Quota), Round 3 (Admission), and Round 4 (Direct Admission). Apply through the TCAS69 system.',
      descriptionTH: 'กำหนดการรับสมัครนักศึกษาใหม่ระดับปริญญาตรี ปีการศึกษา 2569 รอบที่ 1–4 ผ่านระบบ TCAS69',
      image: '/schedule2569_bachelor.png',
      type: 'announcement',
      startDate: '2025-09-10',
      endDate: '2026-06-11',
      ctaText: 'Apply via TCAS',
      ctaTextTH: 'สมัครผ่าน TCAS',
      ctaUrl: 'https://admission.mfu.ac.th/',
      active: true,
      order: 1
    },
    {
      id: 'hl-1',
      title: 'ADT Open House 2025',
      titleTH: 'ADT Open House 2025',
      description: 'Explore our programs, meet our faculty, and discover innovation labs. Join us for an unforgettable day of technology and discovery.',
      descriptionTH: 'สำรวจหลักสูตรของเรา พบกับคณาจารย์ และค้นพบห้องปฏิบัติการนวัตกรรม มาร่วมงานวันที่น่าตื่นเต้นแห่งเทคโนโลยีและการค้นพบ',
      image: 'https://placehold.co/1200x600/0D1830/0CC8D4?text=ADT+Open+House+2025',
      type: 'event',
      startDate: '2025-08-15',
      endDate: '2025-08-16',
      ctaText: 'Register Now',
      ctaTextTH: 'ลงทะเบียนเลย',
      ctaUrl: '#',
      active: true,
      order: 2
    },
    {
      id: 'hl-2',
      title: 'Congratulations Class of 2025!',
      titleTH: 'ยินดีด้วยกับบัณฑิตรุ่น 2025!',
      description: 'We celebrate our outstanding graduates who are ready to transform the digital world. Your journey begins now.',
      descriptionTH: 'เราร่วมแสดงความยินดีกับบัณฑิตที่โดดเด่นของเราที่พร้อมจะเปลี่ยนแปลงโลกดิจิทัล การเดินทางของคุณเริ่มต้นแล้ว',
      image: 'https://placehold.co/1200x600/0D1830/F5A623?text=Congratulations+Class+of+2025',
      type: 'celebration',
      startDate: '2025-07-01',
      ctaText: 'View Ceremony',
      ctaTextTH: 'ดูพิธีมอบปริญญา',
      ctaUrl: '#',
      active: true,
      order: 3
    },
    {
      id: 'hl-3',
      title: 'ADT Research Excellence Awards',
      titleTH: 'รางวัลความเป็นเลิศด้านวิจัย ADT',
      description: 'Three ADT research teams receive national recognition for groundbreaking work in AI, blockchain, and IoT applications.',
      descriptionTH: 'ทีมวิจัย ADT สามทีมได้รับการยอมรับระดับชาติสำหรับผลงานด้าน AI, blockchain และการประยุกต์ใช้ IoT',
      image: 'https://placehold.co/1200x600/0D1830/22EBF8?text=Research+Excellence+Awards',
      type: 'achievement',
      startDate: '2025-06-20',
      ctaText: 'Read More',
      ctaTextTH: 'อ่านเพิ่มเติม',
      ctaUrl: '#',
      active: true,
      order: 4
    },
    {
      id: 'hl-4',
      title: 'Digital Transformation Summer Camp',
      titleTH: 'ค่ายดิจิทัลทรานส์ฟอร์เมชัน ซัมเมอร์',
      description: 'A 5-day intensive bootcamp on AI, web development, and digital entrepreneurship for high school students.',
      descriptionTH: 'บูตแคมป์เข้มข้น 5 วันด้าน AI, web development และการเป็นผู้ประกอบการดิจิทัลสำหรับนักเรียนมัธยม',
      image: 'https://placehold.co/1200x600/0D1830/0CC8D4?text=Summer+Digital+Camp',
      type: 'event',
      startDate: '2025-09-10',
      endDate: '2025-09-14',
      ctaText: 'Apply Now',
      ctaTextTH: 'สมัครเลย',
      ctaUrl: '#',
      active: true,
      order: 5
    }
  ],

  news: [
    {
      id: 'scraped-1',
      title: '"Cattle Detection and Pose Localization Using Computer Vision for Northern Thai Farms" Wins Gold Medal at DIT Award 2026',
      titleTH: 'ผลงาน "Cattle Detection and Pose Localization Using Computer Vision for Northern Thai Farms" คว้ารางวัลชนะเลิศ เหรียญทอง จากเวทีประกวดนวัตกรรมระดับชาติ DIT Award 2026',
      excerpt: 'A research project developing a cattle detection and pose localization system using Computer Vision and AI has won the gold medal at the DIT Award 2026 national innovation competition.',
      excerptTH: 'ผลงานระบบตรวจจับโคและวิเคราะห์ท่าทางด้วยเทคโนโลยี Computer Vision และ AI คว้ารางวัลชนะเลิศเหรียญทองจากเวทีประกวดนวัตกรรมระดับชาติ DIT Award 2026',
      content: 'This project focuses on developing a cattle detection and pose localization system using Computer Vision and AI technology, with the goal of transforming cattle farm management in Northern Thailand into a data-driven, precision operation. The system uses cameras combined with AI models to detect cattle behavior in real time, analyzing activities such as standing, lying, walking, feeding, or signs of health abnormalities, as well as supporting breeding management and planning. The work was conducted under the Master of Science program in Digital Transformation Technology and the Computer Engineering and Communication Research Center at Mae Fah Luang University.\n\nThe competition was held on Friday, March 20, 2026, at the Melia Chiang Mai Hotel, with innovative works from numerous institutions competing.\n\nThe project was supervised by Asst. Prof. Dr. Santichai Wicha. This achievement reflects the capabilities of Thai students in creating digital innovations that can be applied to advance precision agriculture.',
      contentTH: 'ผลงานนี้เป็นการมุ่งพัฒนาระบบตรวจจับโคและวิเคราะห์ท่าทาง (pose localization) ด้วยเทคโนโลยี Computer Vision และ AI เพื่อยกระดับการจัดการฟาร์มโคในภาคเหนือของประเทศไทยให้เป็นการขับเคลื่อนด้วยข้อมูล โดยใช้กล้องร่วมกับโมเดล AI เพื่อตรวจจับพฤติกรรมโคแบบเรียลไทม์ พร้อมวิเคราะห์พฤติกรรม เช่น การยืน นอน เดิน กินอาหาร หรือสัญญาณผิดปกติด้านสุขภาพ โดยเป็นผลงานภายใต้หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาเทคโนโลยีการแปลงเป็นดิจิทัล มหาวิทยาลัยแม่ฟ้าหลวง\n\nการประกวดจัดขึ้นเมื่อวันศุกร์ที่ 20 มีนาคม พ.ศ. 2569 ณ โรงแรมมีเลีย เชียงใหม่\n\nโครงการนี้มี ผศ.ดร.สันติชัย วิชา เป็นอาจารย์ที่ปรึกษา ความสำเร็จครั้งนี้สะท้อนถึงศักยภาพของนักศึกษาไทยในการสร้างสรรค์นวัตกรรมดิจิทัลเพื่อการเกษตรแบบแม่นยำ',
      image: 'https://adt.mfu.ac.th/fileadmin/School_of_IT_file_/News/IT_news/2569/Cattle_Detection_and_Pose_Localization_DIT_Awards_2026/Cattle_Detection_and_Pose_Localization_DIT_Awards_2026_11_Beef.jpg',
      category: 'achievement',
      publishDate: '2026-03-27',
      author: 'Piyawat Paramee',
      authorTH: 'ปิยวัฒน์ ปาระมี',
      featured: true,
      active: true
    },
    {
      id: 'scraped-2',
      title: '"Forklift VR Training" Wins Silver Medal at DIT Award 2026',
      titleTH: 'ผลงาน Forklift VR Training คว้ารางวัลรองชนะเลิศ จากเวที DIT Award 2026',
      excerpt: 'The "Forklift VR Training" research project from the HiTech research group at ADT, Mae Fah Luang University, has won second place (silver medal) at the DIT Award 2026 in the government and private sector organizations category.',
      excerptTH: 'ผลงานวิจัย "Forklift VR Training" จากกลุ่มวิจัย HiTech สำนักวิชา ADT มฟล. ได้รับรางวัลชนะเลิศอันดับที่ 2 (เหรียญเงิน) จากการประกวด DIT Award 2026',
      content: 'The research project "Forklift VR Training" from the Human Interaction and Technology Creativity (HiTech) research group at the School of Applied Digital Technology, Mae Fah Luang University, won second place (silver medal) at the Digital Innovation & Transformation Award 2026 (DIT Award 2026) in the government and private sector organizations category.\n\nThe competition was held on Friday, March 20, 2026, at the Melia Chiang Mai Hotel.\n\n"Forklift VR Training" develops Virtual Reality (VR) technology for learning and skill-building in forklift operation, enabling learners to safely practice in a virtual environment before actual operation, thereby reducing risk and improving training efficiency. The project advisors were Dr. Khemchart Khemawuthananon and Asst. Prof. Dr. Yuttaphong Thongphaeng.',
      contentTH: 'ผลงานวิจัย "Forklift VR Training" จากกลุ่มวิจัย HiTech สำนักวิชาเทคโนโลยีดิจิทัลประยุกต์ มหาวิทยาลัยแม่ฟ้าหลวง ได้รับรางวัลชนะเลิศอันดับที่ 2 (เหรียญเงิน) จากการประกวด DIT Award 2026\n\nการประกวดจัดขึ้นเมื่อวันศุกร์ที่ 20 มีนาคม พ.ศ. 2569 ณ โรงแรมมีเลีย เชียงใหม่\n\nผลงานนี้พัฒนาเทคโนโลยี VR เพื่อฝึกทักษะการขับรถยก ให้ผู้เรียนฝึกในสภาพแวดล้อมเสมือนจริงอย่างปลอดภัย ลดความเสี่ยงและเพิ่มประสิทธิภาพการฝึกอบรม',
      image: 'https://adt.mfu.ac.th/fileadmin/School_of_IT_file_/News/IT_news/2569/Forklift_VR_Training_DIT_Award_2026/Forklift_VR_Training_DIT_Award_20261-1.jpg',
      category: 'achievement',
      publishDate: '2026-03-23',
      author: 'Piyawat Paramee',
      authorTH: 'ปิยวัฒน์ ปาระมี',
      featured: true,
      active: true
    },
    {
      id: 'scraped-3',
      title: '"VR Chiang Saen" Wins Runner-Up at DIT Award 2026 Student Category',
      titleTH: 'ผลงาน "VR Chiang Saen" คว้ารางวัลรองชนะเลิศ จากเวที DIT Award 2026 ระดับนักเรียน/นักศึกษา',
      excerpt: 'Students from the HiTech research group at ADT won second place at DIT Award 2026 with their "VR Chiang Saen" application, recreating the ancient city in an immersive virtual reality experience.',
      excerptTH: 'นักศึกษากลุ่มวิจัย HiTech ADT มฟล. คว้ารางวัลรองชนะเลิศจาก DIT Award 2026 จากผลงาน "VR Chiang Saen" แอปพลิเคชันสร้างประสบการณ์เมืองเชียงแสนโบราณใน Virtual Reality',
      content: 'The "VR Chiang Saen" project by students under the HiTech research group at the School of Applied Digital Technology, Mae Fah Luang University, won second place at the DIT Award 2026 in the student category.\n\n"VR Chiang Saen" is a Virtual Reality application that recreates the historic ancient city of Chiang Saen, allowing users to explore and experience the cultural and historical heritage of the region in an immersive digital environment. The project demonstrates the potential of VR technology in cultural heritage preservation and digital tourism.\n\nThe work was supervised by Dr. Khemchart Khemawuthananon and team members from the HiTech research group.',
      contentTH: 'ผลงาน "VR Chiang Saen" จากนักศึกษาในสังกัดกลุ่มวิจัย HiTech สำนักวิชาเทคโนโลยีดิจิทัลประยุกต์ มหาวิทยาลัยแม่ฟ้าหลวง ได้รับรางวัลชนะเลิศอันดับที่ 2 จากการประกวด DIT Award 2026 ระดับนักศึกษา\n\nผลงาน "VR Chiang Saen" เป็นการพัฒนาแอปพลิเคชัน Virtual Reality ที่จำลองเมืองเชียงแสนโบราณ เพื่อให้ผู้ใช้งานสามารถสำรวจมรดกทางวัฒนธรรมและประวัติศาสตร์ในสภาพแวดล้อมดิจิทัล',
      image: 'https://adt.mfu.ac.th/fileadmin/School_of_IT_file_/News/IT_news/2569/DIT_Awards_2026/DIT_Award_2026_1.jpg',
      category: 'achievement',
      publishDate: '2026-03-23',
      author: 'Piyawat Paramee',
      authorTH: 'ปิยวัฒน์ ปาระมี',
      featured: false,
      active: true
    },
    {
      id: 'scraped-4',
      title: 'ADT Hosts Research Capacity-Building Workshop on Educational Technology with Speaker from Khon Kaen University',
      titleTH: 'สำนักวิชา ADT จัดกิจกรรมเสริมศักยภาพงานวิจัยด้าน Educational Technology โดยวิทยากรจาก ม.ขอนแก่น',
      excerpt: 'The School of Applied Digital Technology held its 2nd Research Collaboration Workshop, featuring a lecture by Prof. Dr. Patcharin Panjaburi from Khon Kaen University on current trends in Educational Technology research.',
      excerptTH: 'สำนักวิชาเทคโนโลยีดิจิทัลประยุกต์ มฟล. จัดกิจกรรมอบรมเพื่อส่งเสริมความร่วมมือวิจัย ครั้งที่ 2 โดยมีศาสตราจารย์ ดร.พัชรินทร์ ปัญจบุรี จาก ม.ขอนแก่น บรรยายด้าน Educational Technology',
      content: 'On March 18, 2026, the School of Applied Digital Technology at Mae Fah Luang University hosted the 2nd Research Collaboration and Academic Capacity Building Workshop under the Research Inspiration Development Project.\n\nThe event was honored by the presence of Professor Dr. Patcharin Panjaburi from Khon Kaen University, who delivered a lecture on "Research Trends that Matter in Educational Technology," covering emerging methodologies, publication strategies, and interdisciplinary applications of technology in education.\n\nThe workshop aimed to strengthen collaborative research ties and provide faculty and graduate students with actionable insights on producing high-quality academic work aligned with international standards.',
      contentTH: 'เมื่อวันที่ 18 มีนาคม 2569 สำนักวิชาเทคโนโลยีดิจิทัลประยุกต์ มหาวิทยาลัยแม่ฟ้าหลวง จัดกิจกรรมอบรมเชิงปฏิบัติการเพื่อส่งเสริมความร่วมมือวิจัยและพัฒนาศักยภาพทางวิชาการ ครั้งที่ 2\n\nได้รับเกียรติจาก ศาสตราจารย์ ดร.พัชรินทร์ ปัญจบุรี จากมหาวิทยาลัยขอนแก่น บรรยายในหัวข้อ Research Trends that Matter in Educational Technology\n\nกิจกรรมนี้มุ่งเสริมสร้างความร่วมมือวิจัยและให้ความรู้แก่คณาจารย์และนักศึกษาบัณฑิตศึกษาในการผลิตผลงานวิชาการที่มีคุณภาพระดับนานาชาติ',
      image: 'https://adt.mfu.ac.th/fileadmin/School_of_IT_file_/News/IT_news/2569/ADT_Update_Research_Educational_Tech/S__46506002_0.jpg',
      category: 'research',
      publishDate: '2026-03-20',
      author: 'Pakpoom Lamprasert',
      authorTH: 'ภาคภูมิ แลมประเสริฐ',
      featured: false,
      active: true
    },
    {
      id: 'scraped-5',
      title: 'ADT Organizes Academic Writing Workshop for Faculty on Publishing Research and Textbooks',
      titleTH: 'สำนักวิชา ADT จัดเวิร์กชอปพัฒนาทักษะการเขียนตำราและบทความวิจัยระดับสูง',
      excerpt: 'The School of Applied Digital Technology organized the 2nd Internal Academic Capacity Building Workshop titled "Becoming an Associate Professor," covering rank promotion procedures and strategies for high-quality academic writing.',
      excerptTH: 'สำนักวิชา ADT จัดกิจกรรม "อบรมเชิงปฏิบัติการพัฒนาศักยภาพทางวิชาการ ครั้งที่ 2" หัวข้อ Becoming an Associate Professor ครอบคลุมขั้นตอนการขอตำแหน่งและการเขียนตำราคุณภาพสูง',
      content: 'On March 9, 2026, the School of Applied Digital Technology organized the 2nd Internal Academic Capacity Building Workshop under the theme "Becoming an Associate Professor!"\n\nThe workshop featured lectures on guidelines and procedures for applying for Associate Professor and writing high-quality textbooks, delivered by Assoc. Prof. Dr. Nacha Chonlamonkon and Assoc. Prof. Dr. Rungsun Chaisricharoen. A second lecture covered approaches to writing high-quality research articles at the Associate Professor level, by Assoc. Prof. Dr. Pannareemol Taemdee and Assoc. Prof. Dr. Nattaphol Oonsri.\n\nThe project aims for at least 60% of participants to develop a conceptual framework for preparing book outlines, driving the school toward academic excellence.',
      contentTH: 'เมื่อวันที่ 9 มีนาคม 2569 สำนักวิชาเทคโนโลยีดิจิทัลประยุกต์ จัดกิจกรรม "อบรมเชิงปฏิบัติการพัฒนาศักยภาพทางวิชาการ ครั้งที่ 2" หัวข้อ Becoming an Associate Professor!\n\nมีการบรรยายโดย รศ.ดร.นชา ชลดำรงค์กุล, รศ.ดร.รังสรรค์ ชัยศรีเจริญ, รศ.ดร.พรรณฤมล เต็มดี และ รศ.ดร.ณัฐพล อุ่นศรี\n\nโครงการนี้มุ่งให้ผู้เข้าร่วมไม่ต่ำกว่าร้อยละ 60 สามารถพัฒนากรอบแนวคิดการเตรียมโครงร่างหนังสือ เพื่อขับเคลื่อนสำนักวิชาสู่ความเป็นเลิศทางวิชาการ',
      image: 'https://adt.mfu.ac.th/fileadmin/School_of_IT_file_/News/IT_news/2569/ADT_Update_Research_Becoming_ASSOC/21e6d360-27d8-429d-bfbf-5698c677e19d.jpg',
      category: 'news',
      publishDate: '2026-03-17',
      author: 'Pakpoom Lamprasert',
      authorTH: 'ภาคภูมิ แลมประเสริฐ',
      featured: false,
      active: true
    },
    {
      id: 'scraped-6',
      title: 'MFU Conducts AI Model Building Training with Google Teachable Machine and No-Code Applications',
      titleTH: 'มฟล. จัดอบรมการสร้างโมเดล AI ด้วย Google Teachable Machine และการประยุกต์ใช้งานแบบ No-code',
      excerpt: 'ADT and the Academic Services Center held a two-day workshop on building AI models using Google Teachable Machine and no-code tools through PictoBlox, for teachers and students from Chiang Rai.',
      excerptTH: 'สำนักวิชา ADT ร่วมกับศูนย์บริการวิชาการ จัดอบรมสร้างโมเดล AI ด้วย Google Teachable Machine และ No-code ผ่าน PictoBlox ให้ครูและนักเรียนในจังหวัดเชียงราย',
      content: 'Mae Fah Luang University, through the School of Applied Digital Technology in collaboration with the Academic Services Center, organized a workshop on "Building AI Models with Google Teachable Machine and No-Code Applications with PictoBlox" on February 21–22, 2026. The opening was presided over by Dr. Khemchart Khemawuthananon, Assistant Dean.\n\nParticipants learned to build and train basic Machine Learning models using Google Teachable Machine, then apply them through PictoBlox, a block-based coding software connecting with microcontroller boards.\n\nThe training covered key concepts including dataset preparation, model training, and model evaluation, promoting hands-on learning for teachers and upper primary and lower secondary school students from Chiang Rai Province.',
      contentTH: 'มหาวิทยาลัยแม่ฟ้าหลวง โดยสำนักวิชาเทคโนโลยีดิจิทัลประยุกต์ ร่วมกับศูนย์บริการวิชาการ จัดโครงการอบรมเชิงปฏิบัติการเรื่อง "การสร้างโมเดล AI ด้วย Google Teachable Machine และการประยุกต์ใช้งานแบบ No-code ด้วย PictoBlox" ณ มหาวิทยาลัยแม่ฟ้าหลวง เมื่อวันที่ 21–22 กุมภาพันธ์ 2569\n\nผู้เข้าร่วมอบรมได้เรียนรู้การสร้างโมเดล Machine Learning ด้วย Google Teachable Machine และการนำไปประยุกต์ใช้ผ่าน PictoBlox\n\nกิจกรรมส่งเสริม Hands-on Learning สำหรับครูและนักเรียนระดับมัธยมในจังหวัดเชียงราย',
      image: 'https://adt.mfu.ac.th/fileadmin/School_of_IT_file_/News/IT_news/2569/ADT_Google_Teachable_Machine/ADT_Google_Teachable_Machine_1.jpg',
      category: 'news',
      publishDate: '2026-02-23',
      author: 'Piyawat Paramee',
      authorTH: 'ปิยวัฒน์ ปาระมี',
      featured: false,
      active: true
    },
    {
      id: 'scraped-7',
      title: 'MFU Launches "ADT MediHack 2026" — 75 Students Develop AI Innovations for Real Clinical Challenges',
      titleTH: 'มฟล. จัด "ADT MediHack 2026" คัด 75 จากกว่า 100 ผู้สมัคร สร้างนวัตกรรม AI แก้โจทย์จริงจากโรงพยาบาลศูนย์การแพทย์',
      excerpt: 'ADT and the MFU Medical Center Hospital co-organized MediHack 2026, selecting 75 students to develop AI-driven healthcare solutions from real clinical problems over two intensive days.',
      excerptTH: 'สำนักวิชา ADT ร่วมกับโรงพยาบาลศูนย์การแพทย์ มฟล. จัด MediHack 2026 คัดเลือก 75 คนจากกว่า 100 ผู้สมัคร พัฒนานวัตกรรม AI แก้ปัญหาจริงในระบบสุขภาพ',
      content: 'The School of Applied Digital Technology at Mae Fah Luang University, in collaboration with the MFU Medical Center Hospital, organized "ADT MediHack – Exploring AI for Healthcare Solution 2026" on February 14–15, 2026, bringing together students from diverse disciplines to develop digital health solutions using AI and UX/UI design.\n\nOver 100 students applied, with 75 selected to participate. At the core of MediHack 2026 was a real-world problem framework from the MFU Medical Center Hospital, covering workflow optimization, patient safety, health information communication, and improving care efficiency.\n\nOrganizers emphasized Human-Centered Design as essential for clinical usability. Pre-competition workshops covered Health Technology, AI, UX/UI design for healthcare, and effective pitching techniques.',
      contentTH: 'สำนักวิชาเทคโนโลยีดิจิทัลประยุกต์ มฟล. ร่วมกับโรงพยาบาลศูนย์การแพทย์ มฟล. จัด "ADT MediHack – Exploring AI for Healthcare Solution 2026" ระหว่างวันที่ 14–15 กุมภาพันธ์ 2569\n\nมีนักศึกษาสมัครกว่า 100 คน คัดเลือกเข้าร่วม 75 คน โจทย์มาจากบริบทจริงของโรงพยาบาลศูนย์การแพทย์ มฟล. ครอบคลุมการเพิ่มประสิทธิภาพกระบวนการทำงาน ความปลอดภัยของผู้ป่วย และการสื่อสารข้อมูลสุขภาพ\n\nผู้จัดเน้นย้ำแนวคิด Human-Centered Design เพื่อให้โซลูชันใช้งานได้จริงในสภาพแวดล้อมคลินิก',
      image: 'https://adt.mfu.ac.th/fileadmin/School_of_IT_file_/News/IT_news/2569/MediHack2026/medihack2026_1.jpg',
      category: 'event',
      publishDate: '2026-02-17',
      author: 'Piyawat Paramee',
      authorTH: 'ปิยวัฒน์ ปาระมี',
      featured: false,
      active: true
    },
    {
      id: 'scraped-8',
      title: 'School of Applied Digital Technology Holds Bai Sri Su Kwan Ceremony for First-Year Students 2025',
      titleTH: 'สำนักวิชาเทคโนโลยีดิจิทัลประยุกต์ มฟล. จัดกิจกรรมบายศรีสู่ขวัญนักศึกษา ประจำปีการศึกษา 2568',
      excerpt: 'ADT organized the traditional Bai Sri Su Kwan ceremony for first-year students of academic year 2025, presided over by Dean Assoc. Prof. Dr. Nacha Chonlamonkon, to welcome and uplift new students.',
      excerptTH: 'สำนักวิชา ADT จัดพิธีบายศรีสู่ขวัญนักศึกษาชั้นปีที่ 1 ปีการศึกษา 2568 โดยมีรองศาสตราจารย์ ดร.นชา ชลดำรงค์กุล คณบดี เป็นประธาน',
      content: 'On January 31, 2026, the School of Applied Digital Technology organized the Bai Sri Su Kwan traditional ceremony for first-year students of academic year 2025, presided over by Assoc. Prof. Dr. Nacha Chonlamonkon, Dean, accompanied by school administrators, faculty, and staff.\n\nThe ceremony was held to uplift the spirits of first-year students as they begin university life, while also learning about Lanna traditions, arts, and culture, and strengthening relationships within the school community. Ceremonial rites were conducted by Pho Nhan Chuchat Jai Kaew.\n\nThe event concluded with a welcoming address from the Dean, after which administrators and faculty tied white ceremonial threads around the wrists of first-year students as a blessing and warm welcome.',
      contentTH: 'เมื่อวันที่ 31 มกราคม 2569 ณ ห้อง 302 อาคาร C5 สำนักวิชาเทคโนโลยีดิจิทัลประยุกต์ จัดพิธีบายศรีสู่ขวัญนักศึกษาชั้นปีที่ 1 ปีการศึกษา 2568 โดยได้รับเกียรติจาก รองศาสตราจารย์ ดร.นชา ชลดำรงค์กุล คณบดี เป็นประธาน\n\nกิจกรรมนี้จัดเพื่อเรียกขวัญกำลังใจนักศึกษาชั้นปีที่ 1 ให้เรียนรู้ประเพณีล้านนา และเสริมสร้างความสัมพันธ์ในสำนักวิชาฯ\n\nปิดท้ายด้วยคณบดีกล่าวต้อนรับ และผูกข้อมือรับขวัญนักศึกษาใหม่',
      image: 'https://adt.mfu.ac.th/fileadmin/School_of_IT_file_/News/IT_news/2569/%E0%B8%9A%E0%B8%B2%E0%B8%A2%E0%B8%A8%E0%B8%A3%E0%B8%B5%E0%B8%AA%E0%B8%B9%E0%B9%88%E0%B8%82%E0%B8%A7%E0%B8%B1%E0%B8%8D_AY2026/dsc06973_optimized_3_11zon.jpg',
      category: 'event',
      publishDate: '2026-02-04',
      author: 'Pakpoom Lamprasert',
      authorTH: 'ภาคภูมิ แลมประเสริฐ',
      featured: false,
      active: true
    },
    {
      id: 'scraped-9',
      title: 'ADT Hosts "Open Ideas to the Digital World" Training for High School Students from Chiang Rai',
      titleTH: 'สำนักวิชา ADT จัดโครงการอบรม "เปิดไอเดีย สู่โลกดิจิทัล" ให้นักเรียนมัธยมจากโรงเรียนเทศบาล 6 นครเชียงราย',
      excerpt: 'ADT and the HiTech Research Group organized the "Open Ideas to the Digital World" training for 129 high school students, providing hands-on experiences across IoT, cybersecurity, multimedia, and AI.',
      excerptTH: 'สำนักวิชา ADT และกลุ่มวิจัย HiTech จัดโครงการ "เปิดไอเดีย สู่โลกดิจิทัล" ให้นักเรียน 129 คนจากโรงเรียนเทศบาล 6 เชียงราย เปิดประสบการณ์จริงด้าน IoT, Cybersecurity, Multimedia และ AI',
      content: 'On January 27, 2025, the School of Digital Technology and the HiTech Research Group organized the "Open Ideas" training program for upper secondary school students from Chiang Rai Municipal School 6, at Laboratory S7A. A total of 129 students participated.\n\nStudents were divided into four activity groups: IoT fundamentals using ESP32 microcontrollers; computer network and cybersecurity fundamentals; multimedia technology and digital content creation; and AI and machine learning applications.\n\nEach group worked with real equipment guided by expert facilitators from the school\'s research teams, reflecting ADT\'s commitment to inspiring the next generation of digital technology professionals from the Chiang Rai region.',
      contentTH: 'เมื่อวันที่ 27 มกราคม 2568 สำนักวิชาดิจิทัลเทคโนโลยีและกลุ่มวิจัย HiTech จัดโครงการอบรมเปิดไอเดียสู่โลกดิจิทัล ให้นักเรียนจากโรงเรียนเทศบาล 6 นครเชียงราย 129 คน ณ ห้องปฏิบัติการ S7A\n\nนักเรียนแบ่งเป็น 4 กลุ่ม: IoT ด้วย ESP32, ความมั่นคงไซเบอร์, มัลติมีเดียและการสร้างเนื้อหาดิจิทัล และการประยุกต์ใช้ AI\n\nทุกกิจกรรมเน้น Hands-on Learning โดยผู้เชี่ยวชาญจากกลุ่มวิจัยของสำนักวิชา',
      image: 'https://adt.mfu.ac.th/fileadmin/School_of_IT_file_/News/IT_news/2569/ADT_T6_Year2/ADT_T6_Year2_1.jpg',
      category: 'event',
      publishDate: '2026-01-30',
      author: 'Piyawat Paramee',
      authorTH: 'ปิยวัฒน์ ปาระมี',
      featured: false,
      active: true
    },
    {
      id: 'scraped-10',
      title: 'DTT Student Shines at High-Tech Training Program in China',
      titleTH: 'นักศึกษา DTT สร้างชื่อในโครงการฝึกอบรมเยาวชนไฮเทค จีน-ไทย',
      excerpt: 'Kwannapa Saelim, a Digital Transformation Technology student at ADT, represented Thailand at the China-Thailand High-tech Young Talent Training Programme in Shanghai and Hangzhou.',
      excerptTH: 'ขวัญนภา แสลิม นักศึกษาสาขา DTT สำนักวิชา ADT มฟล. เป็นตัวแทนไทยในโครงการฝึกอบรมเยาวชนไฮเทค จีน-ไทย ณ เซี่ยงไฮ้และหางโจว',
      content: 'Mae Fah Luang University is proud to celebrate Kwannapa Saelim, a student from the Digital Transformation Technology program, who represented MFU at the China–Thailand High-tech Young Talent Training Programme from November 16–21, 2025, in Shanghai and Hangzhou.\n\nThe program was organized by the Shanghai Advanced Research Institute (SARI) and the Chinese Academy of Sciences (CAS) to mark the 50th Anniversary of diplomatic relations between China and Thailand. It brought together 50 top-tier students — 25 from Thailand and 25 from SARI — to explore cutting-edge fields including Green and Low-Carbon Technologies, Advanced Light Sources, and Big Health Initiatives.\n\nThe initiative focused on building bridges for future academic and industrial collaborations between the two nations.',
      contentTH: 'มหาวิทยาลัยแม่ฟ้าหลวงภูมิใจนำเสนอ ขวัญนภา แสลิม นักศึกษาสาขาเทคโนโลยีการแปลงเป็นดิจิทัล สำนักวิชา ADT ที่เป็นตัวแทน มฟล. เข้าร่วมโครงการ China–Thailand High-tech Young Talent Training Programme ระหว่างวันที่ 16–21 พฤศจิกายน 2568\n\nโครงการจัดโดย SARI และ CAS เพื่อฉลองครบรอบ 50 ปีความสัมพันธ์ทางการทูตจีน-ไทย รวมนักศึกษาชั้นนำ 50 คน สำรวจสาขา Green Technology, Advanced Light Sources และ Big Health\n\nโครงการมุ่งสร้างสะพานความร่วมมือวิชาการและอุตสาหกรรมระหว่างสองประเทศ',
      image: 'https://adt.mfu.ac.th/fileadmin/School_of_IT_file_/News/IT_news/2569/DTT_in_China/619592024_122178038774793501_8036000980688357013_n.jpg',
      category: 'achievement',
      publishDate: '2026-01-29',
      author: 'Pakpoom Lamprasert',
      authorTH: 'ภาคภูมิ แลมประเสริฐ',
      featured: false,
      active: true
    }
  ]
};
