import type { StaffMember } from './types';

/**
 * Scraped staff data from adt.mfu.ac.th (April 2026)
 * Sources:
 *   Page 1 – /faculty/executive-staff.html      → role: dean / assoc_dean
 *   Page 2 – /faculty/academic-staff.html        → role: faculty
 *   Page 3 – /faculty/computer-technical-officers.html → role: staff
 *   Page 4 – /faculty/administrative-officers.html     → role: staff
 *
 * All photo URLs are absolute URLs pointing to adt.mfu.ac.th.
 */
export const scrapedStaff: StaffMember[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // PAGE 1 – Executive Staff
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'nacha-chondamrongkul',
    name: 'Assoc.Prof. Nacha Chondamrongkul, Ph.D.',
    nameTH: 'รองศาสตราจารย์ ดร.นชา ชลดำรงค์กุล',
    title: 'Dean, School of Applied Digital Technology',
    titleTH: 'คณบดีสำนักวิชาเทคโนโลยีดิจิทัลประยุกต์',
    role: 'dean',
    department: 'School of Applied Digital Technology',
    departmentTH: 'สำนักวิชาเทคโนโลยีดิจิทัลประยุกต์',
    email: 'nacha.cho@mfu.ac.th',
    phone: '0 5391 6744',
    photo: '/uploads/staff/SE_Nacha.png',
    bio: 'Associate Professor and Dean of the School of Applied Digital Technology, Mae Fah Luang University.',
    bioTH: 'รองศาสตราจารย์และคณบดีสำนักวิชาเทคโนโลยีดิจิทัลประยุกต์ มหาวิทยาลัยแม่ฟ้าหลวง',
    expertise: ['Software Engineering', 'Digital Technology'],
    expertiseTH: ['วิศวกรรมซอฟต์แวร์', 'เทคโนโลยีดิจิทัล'],
    order: 1,
    active: true,
  },
  {
    id: 'worasak-rueangsirarak',
    name: 'Asst.Prof. Worasak Rueangsirarak, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.วรศักดิ์ เรืองศิรรักษ์',
    title: 'Associate Dean',
    titleTH: 'รองคณบดี',
    role: 'assoc_dean',
    department: 'Digital Transformation Technology',
    departmentTH: 'สาขาวิชาเทคโนโลยีการแปลงเป็นดิจิทัล',
    email: 'worasak.rue@mfu.ac.th',
    phone: '0 5391 7198',
    photo: '/uploads/staff/MTT_Worasak.png',
    bio: 'Assistant Professor and Associate Dean, specializing in Digital Transformation Technology.',
    bioTH: 'ผู้ช่วยศาสตราจารย์และรองคณบดี ผู้เชี่ยวชาญด้านเทคโนโลยีการแปลงเป็นดิจิทัล',
    expertise: ['Digital Transformation', 'Technology Management'],
    expertiseTH: ['การแปลงเป็นดิจิทัล', 'การจัดการเทคโนโลยี'],
    order: 2,
    active: true,
  },
  {
    id: 'pruet-putjorn',
    name: 'Asst.Prof. Pruet Putjorn, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.พฤทธิ์ พุฒจร',
    title: 'Assistant Dean',
    titleTH: 'ผู้ช่วยคณบดี',
    role: 'assoc_dean',
    department: 'Multimedia Technology and Animation',
    departmentTH: 'สาขาวิชาเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว',
    email: 'pruet@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/MTA_Pruet.png',
    bio: 'Assistant Professor and Assistant Dean, specializing in Multimedia Technology and Animation.',
    bioTH: 'ผู้ช่วยศาสตราจารย์และผู้ช่วยคณบดี ผู้เชี่ยวชาญด้านเทคโนโลยีมัลติมีเดีย',
    expertise: ['Multimedia Technology', 'Animation', 'Educational Technology'],
    expertiseTH: ['เทคโนโลยีมัลติมีเดีย', 'การสร้างภาพเคลื่อนไหว', 'เทคโนโลยีการศึกษา'],
    order: 3,
    active: true,
  },
  {
    id: 'paweena-suebsombut',
    name: 'Paweena Suebsombut, Ph.D.',
    nameTH: 'อาจารย์ ดร.ปวีณา สืบสมบัติ',
    title: 'Assistant Dean',
    titleTH: 'ผู้ช่วยคณบดี',
    role: 'assoc_dean',
    department: 'Computer Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    email: 'paweena.sue@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/CE_Paweena.png',
    bio: 'Lecturer and Assistant Dean in Computer Engineering.',
    bioTH: 'อาจารย์และผู้ช่วยคณบดี สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    expertise: ['Computer Engineering', 'Digital Systems'],
    expertiseTH: ['วิศวกรรมคอมพิวเตอร์', 'ระบบดิจิทัล'],
    order: 4,
    active: true,
  },
  {
    id: 'kemachart-kemavuthanon',
    name: 'Kemachart Kemavuthanon, Ph.D.',
    nameTH: 'อาจารย์ ดร.เขมชาติ เขมาวุฒานนท์',
    title: 'Assistant Dean',
    titleTH: 'ผู้ช่วยคณบดี',
    role: 'assoc_dean',
    department: 'Digital and Communication Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมดิจิทัลและการสื่อสาร',
    email: 'Kemachart.kem@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/DCE_Kemachart.png',
    bio: 'Lecturer and Assistant Dean in Digital and Communication Engineering.',
    bioTH: 'อาจารย์และผู้ช่วยคณบดี สาขาวิชาวิศวกรรมดิจิทัลและการสื่อสาร',
    expertise: ['Digital Engineering', 'Communication Engineering'],
    expertiseTH: ['วิศวกรรมดิจิทัล', 'วิศวกรรมการสื่อสาร'],
    order: 5,
    active: true,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PAGE 2 – Academic Staff (Faculty)
  // Department: Computer Engineering (B.Eng.)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'surapol-vorapatratorn',
    name: 'Asst.Prof. Surapol Vorapatratorn, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.สุรพล วรภัทราทร',
    title: 'Assistant Professor (Program Chair)',
    titleTH: 'ผู้ช่วยศาสตราจารย์ (ประธานหลักสูตร)',
    role: 'faculty',
    department: 'Computer Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    email: 'surapol.vor@mfu.ac.th',
    phone: '0 5391 6762',
    photo: '/uploads/staff/CE_Surapol.png',
    bio: 'Assistant Professor and Program Chair of Computer Engineering.',
    bioTH: 'ผู้ช่วยศาสตราจารย์และประธานหลักสูตรวิศวกรรมคอมพิวเตอร์',
    expertise: ['Computer Engineering'],
    expertiseTH: ['วิศวกรรมคอมพิวเตอร์'],
    order: 6,
    active: true,
  },
  {
    id: 'shanmugam-nandagopalan',
    name: 'Prof. Shanmugam Nandagopalan, Ph.D.',
    nameTH: 'Prof. Shanmugam Nandagopalan, Ph.D.',
    title: 'Professor',
    titleTH: 'ศาสตราจารย์',
    role: 'faculty',
    department: 'Computer Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    email: 'shanmugamnandagopalan@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/CE_S.Nanda.png',
    bio: 'Professor in Computer Engineering.',
    bioTH: 'ศาสตราจารย์ สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    expertise: ['Computer Engineering'],
    expertiseTH: ['วิศวกรรมคอมพิวเตอร์'],
    order: 7,
    active: true,
  },
  {
    id: 'khwunta-kirimasthong',
    name: 'Asst.Prof. Khwunta Kirimasthong, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.ขวัญตา คีรีมาศทอง',
    title: 'Assistant Professor',
    titleTH: 'ผู้ช่วยศาสตราจารย์',
    role: 'faculty',
    department: 'Computer Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    email: 'khwunta.kir@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/CE_Khwunta.png',
    bio: 'Assistant Professor in Computer Engineering.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    expertise: ['Computer Engineering'],
    expertiseTH: ['วิศวกรรมคอมพิวเตอร์'],
    order: 8,
    active: true,
  },
  {
    id: 'pattaramon-vuttipittayamongkol',
    name: 'Asst.Prof. Pattaramon Vuttipittayamongkol, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.ภัทรมน วุฒิพิทยามงคล',
    title: 'Assistant Professor',
    titleTH: 'ผู้ช่วยศาสตราจารย์',
    role: 'faculty',
    department: 'Computer Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    email: 'pattaramon.vut@mfu.ac.th',
    phone: '0 5391 6762',
    photo: '/uploads/staff/CE_Pattaramon.png',
    bio: 'Assistant Professor in Computer Engineering.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    expertise: ['Computer Engineering', 'Image Processing'],
    expertiseTH: ['วิศวกรรมคอมพิวเตอร์', 'การประมวลผลภาพ'],
    order: 9,
    active: true,
  },
  {
    id: 'narong-chaiwut',
    name: 'Narong Chaiwut',
    nameTH: 'อาจารย์ณรงค์ ชัยวุฒิ',
    title: 'Lecturer (On study leave)',
    titleTH: 'อาจารย์ (ลาศึกษาต่อ)',
    role: 'faculty',
    department: 'Computer Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    email: 'narong.cha@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/CE_Narong.png',
    bio: 'Lecturer in Computer Engineering (currently on study leave).',
    bioTH: 'อาจารย์สาขาวิชาวิศวกรรมคอมพิวเตอร์ (ลาศึกษาต่อ)',
    expertise: ['Computer Engineering'],
    expertiseTH: ['วิศวกรรมคอมพิวเตอร์'],
    order: 10,
    active: true,
  },
  {
    id: 'chayapol-kamyod',
    name: 'Asst.Prof. Chayapol Kamyod, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.ชยพล คำยอด',
    title: 'Assistant Professor',
    titleTH: 'ผู้ช่วยศาสตราจารย์',
    role: 'faculty',
    department: 'Computer Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    email: 'chayapol.kam@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/CE_Chayapol.png',
    bio: 'Assistant Professor in Computer Engineering.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    expertise: ['Computer Engineering', 'Wireless Communication'],
    expertiseTH: ['วิศวกรรมคอมพิวเตอร์', 'การสื่อสารไร้สาย'],
    order: 11,
    active: true,
  },
  {
    id: 'mahamah-sebakor',
    name: 'Asst.Prof. Mahamah Sebakor, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.มาหะมะ เซะบากอ',
    title: 'Assistant Professor',
    titleTH: 'ผู้ช่วยศาสตราจารย์',
    role: 'faculty',
    department: 'Computer Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    email: 'mahamah.seb@mfu.ac.th',
    phone: '0 5391 6401',
    photo: '/uploads/staff/CE_Mahama.png',
    bio: 'Assistant Professor in Computer Engineering.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    expertise: ['Computer Engineering'],
    expertiseTH: ['วิศวกรรมคอมพิวเตอร์'],
    order: 12,
    active: true,
  },

  // Department: Digital and Communication Engineering (B.Eng.)
  {
    id: 'suppakarn-chansareewittaya',
    name: 'Asst.Prof. Suppakarn Chansareewittaya, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.ศุภกานต์ จันทร์เสรีวิทยา',
    title: 'Assistant Professor (Program Chair)',
    titleTH: 'ผู้ช่วยศาสตราจารย์ (ประธานหลักสูตร)',
    role: 'faculty',
    department: 'Digital and Communication Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมดิจิทัลและการสื่อสาร',
    email: 'suppakarn.cha@mfu.ac.th',
    phone: '0 5391 6932',
    photo: '/uploads/staff/DCE_Suppakarn.png',
    bio: 'Assistant Professor and Program Chair of Digital and Communication Engineering.',
    bioTH: 'ผู้ช่วยศาสตราจารย์และประธานหลักสูตรวิศวกรรมดิจิทัลและการสื่อสาร',
    expertise: ['Digital Engineering', 'Communication Systems'],
    expertiseTH: ['วิศวกรรมดิจิทัล', 'ระบบการสื่อสาร'],
    order: 13,
    active: true,
  },
  {
    id: 'sirikan-chucherd',
    name: 'Asst.Prof. Sirikan Chucherd, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.ศิริกานต์ ชูเชิด',
    title: 'Assistant Professor',
    titleTH: 'ผู้ช่วยศาสตราจารย์',
    role: 'faculty',
    department: 'Digital and Communication Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมดิจิทัลและการสื่อสาร',
    email: 'sirikan@mfu.ac.th',
    phone: '0 5391 6763',
    photo: '/uploads/staff/DCE_Sirikan.png',
    bio: 'Assistant Professor in Digital and Communication Engineering.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ สาขาวิชาวิศวกรรมดิจิทัลและการสื่อสาร',
    expertise: ['Digital Engineering', 'Signal Processing'],
    expertiseTH: ['วิศวกรรมดิจิทัล', 'การประมวลผลสัญญาณ'],
    order: 14,
    active: true,
  },
  {
    id: 'titiya-chomngern',
    name: 'Titiya Chomngern, Ph.D.',
    nameTH: 'อาจารย์ ดร.ฐิติยา ชมเงิน',
    title: 'Lecturer',
    titleTH: 'อาจารย์',
    role: 'faculty',
    department: 'Digital and Communication Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมดิจิทัลและการสื่อสาร',
    email: 'Titiya.cho@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/DCE_Titiya.png',
    bio: 'Lecturer in Digital and Communication Engineering.',
    bioTH: 'อาจารย์ สาขาวิชาวิศวกรรมดิจิทัลและการสื่อสาร',
    expertise: ['Digital Engineering'],
    expertiseTH: ['วิศวกรรมดิจิทัล'],
    order: 15,
    active: true,
  },
  {
    id: 'teeravisit-laohapensaeng',
    name: 'Asst.Prof. Teeravisit Laohapensaeng, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.ธีรวิศิฏฐ์ เลาหะเพ็ญแสง',
    title: 'Assistant Professor',
    titleTH: 'ผู้ช่วยศาสตราจารย์',
    role: 'faculty',
    department: 'Digital and Communication Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมดิจิทัลและการสื่อสาร',
    email: 'Teeravisit.lao@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/DCE_Teeravisit.png',
    bio: 'Assistant Professor in Digital and Communication Engineering.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ สาขาวิชาวิศวกรรมดิจิทัลและการสื่อสาร',
    expertise: ['Digital Engineering', 'Embedded Systems'],
    expertiseTH: ['วิศวกรรมดิจิทัล', 'ระบบฝังตัว'],
    order: 16,
    active: true,
  },

  // Department: Software Engineering (B.Eng.)
  {
    id: 'prasara-jakkaew',
    name: 'Prasara Jakkaew, Ph.D.',
    nameTH: 'อาจารย์ ดร.ปรัสรา จักรแก้ว',
    title: 'Lecturer (Program Chair)',
    titleTH: 'อาจารย์ (ประธานหลักสูตร)',
    role: 'faculty',
    department: 'Software Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมซอฟต์แวร์',
    email: 'prasara.jak@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/SE_Prasara.png',
    bio: 'Lecturer and Program Chair of Software Engineering.',
    bioTH: 'อาจารย์และประธานหลักสูตรวิศวกรรมซอฟต์แวร์',
    expertise: ['Software Engineering'],
    expertiseTH: ['วิศวกรรมซอฟต์แวร์'],
    order: 17,
    active: true,
  },
  {
    id: 'wacharawan-intayoad',
    name: 'Wacharawan Intayoad, Ph.D.',
    nameTH: 'อาจารย์ ดร.วัชราวรรณ อินทยศ',
    title: 'Lecturer',
    titleTH: 'อาจารย์',
    role: 'faculty',
    department: 'Software Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมซอฟต์แวร์',
    email: 'wacharawan.int@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/SE_Wacharawan.png',
    bio: 'Lecturer in Software Engineering.',
    bioTH: 'อาจารย์ สาขาวิชาวิศวกรรมซอฟต์แวร์',
    expertise: ['Software Engineering', 'Machine Learning'],
    expertiseTH: ['วิศวกรรมซอฟต์แวร์', 'การเรียนรู้ของเครื่อง'],
    order: 18,
    active: true,
  },
  {
    id: 'nang-hsu-mon-pyae',
    name: 'Nang Hsu Mon Pyae, Ph.D.',
    nameTH: 'Nang Hsu Mon Pyae, Ph.D.',
    title: 'Lecturer',
    titleTH: 'อาจารย์',
    role: 'faculty',
    department: 'Software Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมซอฟต์แวร์',
    email: 'nanghsumonpyae@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/SE_Hsu.png',
    bio: 'Lecturer in Software Engineering.',
    bioTH: 'อาจารย์ สาขาวิชาวิศวกรรมซอฟต์แวร์',
    expertise: ['Software Engineering'],
    expertiseTH: ['วิศวกรรมซอฟต์แวร์'],
    order: 19,
    active: true,
  },
  {
    id: 'sujitra-arwatchananukul',
    name: 'Asst.Prof. Sujitra Arwatchananukul, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.สุจิตรา อาวัชนานุกุล',
    title: 'Assistant Professor',
    titleTH: 'ผู้ช่วยศาสตราจารย์',
    role: 'faculty',
    department: 'Software Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมซอฟต์แวร์',
    email: 'sujitra.arw@mfu.ac.th',
    phone: '0 5391 6765',
    photo: '/uploads/staff/SE_Sujitra.png',
    bio: 'Assistant Professor in Software Engineering.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ สาขาวิชาวิศวกรรมซอฟต์แวร์',
    expertise: ['Software Engineering', 'Data Mining'],
    expertiseTH: ['วิศวกรรมซอฟต์แวร์', 'การขุดข้อมูล'],
    order: 20,
    active: true,
  },
  {
    id: 'vittayasak-rujivorakul',
    name: 'Vittayasak Rujivorakul',
    nameTH: 'อาจารย์วิทยาศักดิ์ รุจิวรกุล',
    title: 'Lecturer',
    titleTH: 'อาจารย์',
    role: 'faculty',
    department: 'Software Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมซอฟต์แวร์',
    email: 'vittayasak@mfu.ac.th',
    phone: '0 5391 6075',
    photo: '/uploads/staff/SE_Vittayasak.png',
    bio: 'Lecturer in Software Engineering.',
    bioTH: 'อาจารย์ สาขาวิชาวิศวกรรมซอฟต์แวร์',
    expertise: ['Software Engineering'],
    expertiseTH: ['วิศวกรรมซอฟต์แวร์'],
    order: 21,
    active: true,
  },
  {
    id: 'tew-hongthong',
    name: 'Tew Hongthong',
    nameTH: 'อาจารย์ทิว หงษ์ทอง',
    title: 'Lecturer',
    titleTH: 'อาจารย์',
    role: 'faculty',
    department: 'Software Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมซอฟต์แวร์',
    email: 'tew.hon@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/SE_Tew.png',
    bio: 'Lecturer in Software Engineering.',
    bioTH: 'อาจารย์ สาขาวิชาวิศวกรรมซอฟต์แวร์',
    expertise: ['Software Engineering'],
    expertiseTH: ['วิศวกรรมซอฟต์แวร์'],
    order: 22,
    active: true,
  },

  // Department: Digital Technology for Business Innovation (B.Tech.)
  {
    id: 'nikorn-rongbutsri',
    name: 'Nikorn Rongbutsri, Ph.D.',
    nameTH: 'อาจารย์ ดร.นิกรณ์ หร่องบุตรศรี',
    title: 'Lecturer (Program Chair)',
    titleTH: 'อาจารย์ (ประธานหลักสูตร)',
    role: 'faculty',
    department: 'Digital Technology for Business Innovation',
    departmentTH: 'สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    email: 'nikorn@mfu.ac.th',
    phone: '0 5391 6765',
    photo: '/uploads/staff/DTBI_Nikorn.png',
    bio: 'Lecturer and Program Chair of Digital Technology for Business Innovation.',
    bioTH: 'อาจารย์และประธานหลักสูตรเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    expertise: ['Digital Technology', 'Business Innovation', 'E-Learning'],
    expertiseTH: ['เทคโนโลยีดิจิทัล', 'นวัตกรรมทางธุรกิจ', 'อีเลิร์นนิง'],
    order: 23,
    active: true,
  },
  {
    id: 'soontarin-nupap',
    name: 'Soontarin Nupap, Ph.D.',
    nameTH: 'อาจารย์ ดร.สุนทรินทร์ นุภาพ',
    title: 'Lecturer',
    titleTH: 'อาจารย์',
    role: 'faculty',
    department: 'Digital Technology for Business Innovation',
    departmentTH: 'สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    email: 'soontarin@mfu.ac.th',
    phone: '0 5391 6755',
    photo: '/uploads/staff/DTBI_Soontarin.png',
    bio: 'Lecturer in Digital Technology for Business Innovation.',
    bioTH: 'อาจารย์ สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    expertise: ['Digital Technology', 'Business Analytics'],
    expertiseTH: ['เทคโนโลยีดิจิทัล', 'การวิเคราะห์ทางธุรกิจ'],
    order: 24,
    active: true,
  },
  {
    id: 'patcharaporn-panwong',
    name: 'Patcharaporn Panwong, Ph.D.',
    nameTH: 'อาจารย์ ดร.พัชราภรณ์ พรรณวงค์',
    title: 'Lecturer',
    titleTH: 'อาจารย์',
    role: 'faculty',
    department: 'Digital Technology for Business Innovation',
    departmentTH: 'สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    email: 'patcharaporn.pan@mfu.ac.th',
    phone: '0 5391 6763',
    photo: '/uploads/staff/DTBI_Patcharaporn.png',
    bio: 'Lecturer in Digital Technology for Business Innovation.',
    bioTH: 'อาจารย์ สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    expertise: ['Digital Technology', 'Data Science'],
    expertiseTH: ['เทคโนโลยีดิจิทัล', 'วิทยาการข้อมูล'],
    order: 25,
    active: true,
  },
  {
    id: 'teanjit-sutthaluang',
    name: 'Teanjit Sutthaluang',
    nameTH: 'อาจารย์เตือนจิต สุทธหลวง',
    title: 'Lecturer',
    titleTH: 'อาจารย์',
    role: 'faculty',
    department: 'Digital Technology for Business Innovation',
    departmentTH: 'สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    email: 'ternchit@mfu.ac.th',
    phone: '0 5391 6756',
    photo: '/uploads/staff/DTBI_Teanjit.png',
    bio: 'Lecturer in Digital Technology for Business Innovation.',
    bioTH: 'อาจารย์ สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    expertise: ['Digital Technology'],
    expertiseTH: ['เทคโนโลยีดิจิทัล'],
    order: 26,
    active: true,
  },
  {
    id: 'nilubon-kurubanjerdjit',
    name: 'Asst.Prof. Nilubon Kurubanjerdjit, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.นิลุบล คุรุบรรเจิดจิต',
    title: 'Assistant Professor',
    titleTH: 'ผู้ช่วยศาสตราจารย์',
    role: 'faculty',
    department: 'Digital Technology for Business Innovation',
    departmentTH: 'สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    email: 'Nilubon.kur@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/DTBI_Nilubon.png',
    bio: 'Assistant Professor in Digital Technology for Business Innovation.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    expertise: ['Bioinformatics', 'Digital Technology'],
    expertiseTH: ['ชีวสารสนเทศ', 'เทคโนโลยีดิจิทัล'],
    order: 27,
    active: true,
  },
  {
    id: 'waralak-chongdarakul',
    name: 'Asst.Prof. Waralak Chongdarakul, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.วราลักษณ์ ช่องดารากุล',
    title: 'Assistant Professor',
    titleTH: 'ผู้ช่วยศาสตราจารย์',
    role: 'faculty',
    department: 'Digital Technology for Business Innovation',
    departmentTH: 'สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    email: 'waralak@mfu.ac.th',
    phone: '0 5391 6758',
    photo: '/uploads/staff/DTBI_Waralak.png',
    bio: 'Assistant Professor in Digital Technology for Business Innovation.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    expertise: ['Digital Technology', 'Information Systems'],
    expertiseTH: ['เทคโนโลยีดิจิทัล', 'ระบบสารสนเทศ'],
    order: 28,
    active: true,
  },
  {
    id: 'charoenchai-wongwatkit',
    name: 'Asst.Prof.Acting Sub-Lt. Charoenchai Wongwatkit, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ว่าที่ร้อยตรี ดร.เจริญชัย วงศ์วัฒน์กิจ',
    title: 'Assistant Professor',
    titleTH: 'ผู้ช่วยศาสตราจารย์',
    role: 'faculty',
    department: 'Digital Technology for Business Innovation',
    departmentTH: 'สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    email: 'charoenchai.won@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/DTBI_Charoenchai.png',
    bio: 'Assistant Professor in Digital Technology for Business Innovation.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ สาขาวิชาเทคโนโลยีดิจิทัลเพื่อนวัตกรรมทางธุรกิจ',
    expertise: ['Digital Technology', 'Adaptive Learning'],
    expertiseTH: ['เทคโนโลยีดิจิทัล', 'การเรียนรู้แบบปรับตัว'],
    order: 29,
    active: true,
  },

  // Department: Multimedia Technology and Animation (B.Tech.)
  {
    id: 'nontawat-thongsibsong',
    name: 'Nontawat Thongsibsong',
    nameTH: 'อาจารย์นนทวรรษ ธงสิบสอง',
    title: 'Lecturer (Program Chair)',
    titleTH: 'อาจารย์ (ประธานหลักสูตร)',
    role: 'faculty',
    department: 'Multimedia Technology and Animation',
    departmentTH: 'สาขาวิชาเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว',
    email: 'nontawat@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/MTA_Nontawat.png',
    bio: 'Lecturer and Program Chair of Multimedia Technology and Animation.',
    bioTH: 'อาจารย์และประธานหลักสูตรเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว',
    expertise: ['Multimedia Technology', 'Animation', '3D Modeling'],
    expertiseTH: ['เทคโนโลยีมัลติมีเดีย', 'การสร้างภาพเคลื่อนไหว', '3D โมเดลลิง'],
    order: 30,
    active: true,
  },
  {
    id: 'yootthapong-tongpaeng',
    name: 'Asst.Prof. Yootthapong Tongpaeng, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.ยุทธพงษ์ ทองแพง',
    title: 'Assistant Professor',
    titleTH: 'ผู้ช่วยศาสตราจารย์',
    role: 'faculty',
    department: 'Multimedia Technology and Animation',
    departmentTH: 'สาขาวิชาเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว',
    email: 'yootthapong.ton@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/MTA_Yootthapong.png',
    bio: 'Assistant Professor in Multimedia Technology and Animation.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ สาขาวิชาเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว',
    expertise: ['Multimedia Technology', 'Human-Computer Interaction'],
    expertiseTH: ['เทคโนโลยีมัลติมีเดีย', 'ปฏิสัมพันธ์มนุษย์กับคอมพิวเตอร์'],
    order: 31,
    active: true,
  },
  {
    id: 'karn-soponronnarit',
    name: 'Karn Soponronnarit',
    nameTH: 'อาจารย์กานต์ โสภณรณฤทธิ์',
    title: 'Lecturer (On study leave)',
    titleTH: 'อาจารย์ (ลาศึกษาต่อ)',
    role: 'faculty',
    department: 'Multimedia Technology and Animation',
    departmentTH: 'สาขาวิชาเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว',
    email: 'karn.sop@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/MTA_Karn.png',
    bio: 'Lecturer in Multimedia Technology and Animation (currently on study leave).',
    bioTH: 'อาจารย์สาขาวิชาเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว (ลาศึกษาต่อ)',
    expertise: ['Multimedia Technology', 'Animation'],
    expertiseTH: ['เทคโนโลยีมัลติมีเดีย', 'การสร้างภาพเคลื่อนไหว'],
    order: 32,
    active: true,
  },
  {
    id: 'thanpahtt-chaichombhoo',
    name: 'Thanpahtt Chaichombhoo',
    nameTH: 'อาจารย์ฐานปัทม์ ไชยชมภู',
    title: 'Lecturer',
    titleTH: 'อาจารย์',
    role: 'faculty',
    department: 'Multimedia Technology and Animation',
    departmentTH: 'สาขาวิชาเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว',
    email: 'thanpahtt.cha@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/MTA_Thanphatt.png',
    bio: 'Lecturer in Multimedia Technology and Animation.',
    bioTH: 'อาจารย์ สาขาวิชาเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว',
    expertise: ['Multimedia Technology', 'Digital Arts'],
    expertiseTH: ['เทคโนโลยีมัลติมีเดีย', 'ศิลปะดิจิทัล'],
    order: 33,
    active: true,
  },
  {
    id: 'banphot-nobaew',
    name: 'Banphot Nobaew, Ph.D.',
    nameTH: 'อาจารย์ ดร.บรรพจณ์ โนแบ้ว',
    title: 'Lecturer',
    titleTH: 'อาจารย์',
    role: 'faculty',
    department: 'Multimedia Technology and Animation',
    departmentTH: 'สาขาวิชาเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว',
    email: 'banphot@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/MTA_Banphot.png',
    bio: 'Lecturer in Multimedia Technology and Animation.',
    bioTH: 'อาจารย์ สาขาวิชาเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว',
    expertise: ['Multimedia Technology', 'Virtual Reality', 'Serious Games'],
    expertiseTH: ['เทคโนโลยีมัลติมีเดีย', 'ความเป็นจริงเสมือน', 'เกมเพื่อการศึกษา'],
    order: 34,
    active: true,
  },
  {
    id: 'ratchanon-nobnop',
    name: 'Ratchanon Nobnop',
    nameTH: 'อาจารย์รัชชานนท์ นอบนพ',
    title: 'Lecturer (On study leave)',
    titleTH: 'อาจารย์ (ลาศึกษาต่อ)',
    role: 'faculty',
    department: 'Multimedia Technology and Animation',
    departmentTH: 'สาขาวิชาเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว',
    email: 'ratchanon.nob@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/MTA_Ratchanon.png',
    bio: 'Lecturer in Multimedia Technology and Animation (currently on study leave).',
    bioTH: 'อาจารย์สาขาวิชาเทคโนโลยีมัลติมีเดียและการสร้างภาพเคลื่อนไหว (ลาศึกษาต่อ)',
    expertise: ['Multimedia Technology'],
    expertiseTH: ['เทคโนโลยีมัลติมีเดีย'],
    order: 35,
    active: true,
  },

  // Department: Digital Transformation Technology (M.Tech. – Master's)
  {
    id: 'surapong-uttama',
    name: 'Asst.Prof. Surapong Uttama, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.สุรพงษ์ อุตมา',
    title: 'Assistant Professor (Program Chair)',
    titleTH: 'ผู้ช่วยศาสตราจารย์ (ประธานหลักสูตร)',
    role: 'faculty',
    department: 'Digital Transformation Technology',
    departmentTH: 'สาขาวิชาเทคโนโลยีการแปลงเป็นดิจิทัล',
    email: 'surapong@mfu.ac.th',
    phone: '',
    photo: '/uploads/staff/MTT_Surapong.png',
    bio: 'Assistant Professor and Program Chair of Digital Transformation Technology (Master\'s).',
    bioTH: 'ผู้ช่วยศาสตราจารย์และประธานหลักสูตรเทคโนโลยีการแปลงเป็นดิจิทัล (ระดับปริญญาโท)',
    expertise: ['Digital Transformation', 'Robotics', 'AI'],
    expertiseTH: ['การแปลงเป็นดิจิทัล', 'หุ่นยนต์', 'ปัญญาประดิษฐ์'],
    order: 36,
    active: true,
  },
  {
    id: 'santichai-wicha',
    name: 'Asst.Prof. Santichai Wicha, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ ดร.สันติชัย วิชา',
    title: 'Assistant Professor',
    titleTH: 'ผู้ช่วยศาสตราจารย์',
    role: 'faculty',
    department: 'Digital Transformation Technology',
    departmentTH: 'สาขาวิชาเทคโนโลยีการแปลงเป็นดิจิทัล',
    email: 'santichai@mfu.ac.th',
    phone: '0 5391 6758',
    photo: '/uploads/staff/MTT_Santichai.png',
    bio: 'Assistant Professor in Digital Transformation Technology.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ สาขาวิชาเทคโนโลยีการแปลงเป็นดิจิทัล',
    expertise: ['Digital Transformation', 'Network Security'],
    expertiseTH: ['การแปลงเป็นดิจิทัล', 'ความมั่นคงเครือข่าย'],
    order: 37,
    active: true,
  },

  // Department: Computer Engineering (M.Eng. / Ph.D.)
  {
    id: 'thongchai-yooyatiwong',
    name: 'Asst.Prof.Gp.Capt. Thongchai Yooyatiwong, Ph.D.',
    nameTH: 'ผู้ช่วยศาสตราจารย์ นาวาอากาศเอก ดร.ธงชัย อยู่ญาติวงศ์',
    title: 'Assistant Professor (Senior Lecturer)',
    titleTH: 'ผู้ช่วยศาสตราจารย์ (อาจารย์อาวุโส)',
    role: 'faculty',
    department: 'Computer Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    email: 'Thongchai@mfu.ac.th',
    phone: '0 5391 7200',
    photo: '/uploads/staff/M.CE_Thongchai.png',
    bio: 'Assistant Professor (Senior Lecturer) in Computer Engineering.',
    bioTH: 'ผู้ช่วยศาสตราจารย์ (อาจารย์อาวุโส) สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    expertise: ['Computer Engineering', 'Embedded Systems', 'IoT'],
    expertiseTH: ['วิศวกรรมคอมพิวเตอร์', 'ระบบฝังตัว', 'อินเทอร์เน็ตของสรรพสิ่ง'],
    order: 38,
    active: true,
  },
  {
    id: 'roungsan-chaisricharoen',
    name: 'Assoc.Prof. Roungsan Chaisricharoen, Ph.D.',
    nameTH: 'รองศาสตราจารย์ ดร.รังสรรค์ ชัยศรีเจริญ',
    title: 'Associate Professor',
    titleTH: 'รองศาสตราจารย์',
    role: 'faculty',
    department: 'Computer Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    email: 'roungsan.cha@mfu.ac.th',
    phone: '0 5391 6757',
    photo: '/uploads/staff/M.CE_Roungsan.png',
    bio: 'Associate Professor in Computer Engineering.',
    bioTH: 'รองศาสตราจารย์ สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    expertise: ['Computer Engineering', 'VLSI Design', 'Digital Systems'],
    expertiseTH: ['วิศวกรรมคอมพิวเตอร์', 'การออกแบบ VLSI', 'ระบบดิจิทัล'],
    order: 39,
    active: true,
  },
  {
    id: 'punnarumol-temdee',
    name: 'Assoc.Prof. Punnarumol Temdee, Ph.D.',
    nameTH: 'รองศาสตราจารย์ ดร.พรรณฤมล เต็มดี',
    title: 'Associate Professor',
    titleTH: 'รองศาสตราจารย์',
    role: 'faculty',
    department: 'Computer Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    email: 'Punnarumol@mfu.ac.th',
    phone: '0 5391 6758',
    photo: '/uploads/staff/M.CE_Punnarumol.png',
    bio: 'Associate Professor in Computer Engineering.',
    bioTH: 'รองศาสตราจารย์ สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    expertise: ['Computer Engineering', 'Social Networks', 'Wireless Networks'],
    expertiseTH: ['วิศวกรรมคอมพิวเตอร์', 'เครือข่ายสังคม', 'เครือข่ายไร้สาย'],
    order: 40,
    active: true,
  },
  {
    id: 'nattapol-aunsri',
    name: 'Assoc.Prof. Nattapol Aunsri, Ph.D.',
    nameTH: 'รองศาสตราจารย์ ดร.ณัฐพล อุ่นศรี',
    title: 'Associate Professor',
    titleTH: 'รองศาสตราจารย์',
    role: 'faculty',
    department: 'Computer Engineering',
    departmentTH: 'สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    email: 'Nattapol.aun@mfu.ac.th',
    phone: '0 5391 6765',
    photo: '/uploads/staff/M.CE_Nattapol.png',
    bio: 'Associate Professor in Computer Engineering.',
    bioTH: 'รองศาสตราจารย์ สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    expertise: ['Computer Engineering', 'Signal Processing', 'Biomedical Engineering'],
    expertiseTH: ['วิศวกรรมคอมพิวเตอร์', 'การประมวลผลสัญญาณ', 'วิศวกรรมชีวการแพทย์'],
    order: 41,
    active: true,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PAGE 3 – Computer Technical Officers (นักวิชาการคอมพิวเตอร์)
  // role: staff
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'sittichai-thandaung',
    name: 'Sittichai Thandaung',
    nameTH: 'นายสิทธิชัย แทนด้วง',
    title: 'Computer Technical Officer',
    titleTH: 'นักวิชาการคอมพิวเตอร์',
    role: 'staff',
    department: 'Computer Technical Officers',
    departmentTH: 'บุคลากรสายปฏิบัติการ (นักวิชาการคอมพิวเตอร์)',
    email: 'sittichai@mfu.ac.th',
    phone: '0 5391 7165',
    photo: '/uploads/staff/P_Chai.png',
    bio: '',
    bioTH: '',
    expertise: [],
    expertiseTH: [],
    order: 42,
    active: true,
  },
  {
    id: 'siwaporn-bunsomwon',
    name: 'Siwaporn Bunsomwon',
    nameTH: 'นางสาวศิวพร บุญสมวล',
    title: 'Computer Technical Officer',
    titleTH: 'นักวิชาการคอมพิวเตอร์',
    role: 'staff',
    department: 'Computer Technical Officers',
    departmentTH: 'บุคลากรสายปฏิบัติการ (นักวิชาการคอมพิวเตอร์)',
    email: 'siwaporn.boo@mfu.ac.th',
    phone: '0 5391 7166',
    photo: '/uploads/staff/P_Si.png',
    bio: '',
    bioTH: '',
    expertise: [],
    expertiseTH: [],
    order: 43,
    active: true,
  },
  {
    id: 'piyawat-paramee',
    name: 'Piyawat Paramee',
    nameTH: 'นายปิยวัฒน์ ปาระมี',
    title: 'Computer Technical Officer',
    titleTH: 'นักวิชาการคอมพิวเตอร์',
    role: 'staff',
    department: 'Computer Technical Officers',
    departmentTH: 'บุคลากรสายปฏิบัติการ (นักวิชาการคอมพิวเตอร์)',
    email: 'piyawat.par@mfu.ac.th',
    phone: '0 5391 7198',
    photo: '/uploads/staff/P_Boat.png',
    bio: '',
    bioTH: '',
    expertise: [],
    expertiseTH: [],
    order: 44,
    active: true,
  },
  {
    id: 'thapakorn-sasiwimonlak',
    name: 'Acting Sub-Lt. Thapakorn Sasiwimonlak',
    nameTH: 'ว่าที่ร้อยตรีฐาปกรณ์ ศศิวิมลลักษณ์',
    title: 'Computer Technical Officer',
    titleTH: 'นักวิชาการคอมพิวเตอร์',
    role: 'staff',
    department: 'Computer Technical Officers',
    departmentTH: 'บุคลากรสายปฏิบัติการ (นักวิชาการคอมพิวเตอร์)',
    email: 'thapakorn.sas@mfu.ac.th',
    phone: '0 5391 7166',
    photo: '/uploads/staff/P_aar.png',
    bio: '',
    bioTH: '',
    expertise: [],
    expertiseTH: [],
    order: 45,
    active: true,
  },
  {
    id: 'pakpoom-prommoon',
    name: 'Acting Sub-Lt. Pakpoom Prommoon',
    nameTH: 'ว่าที่ร้อยตรีภาคภูมิ พรมมูล',
    title: 'Computer Technical Officer',
    titleTH: 'นักวิชาการคอมพิวเตอร์',
    role: 'staff',
    department: 'Computer Technical Officers',
    departmentTH: 'บุคลากรสายปฏิบัติการ (นักวิชาการคอมพิวเตอร์)',
    email: 'pakpoom.pro@mfu.ac.th',
    phone: '0 5391 7165',
    photo: '/uploads/staff/P_Petch.png',
    bio: '',
    bioTH: '',
    expertise: [],
    expertiseTH: [],
    order: 46,
    active: true,
  },
  {
    id: 'jetmanus-ratisaksunthon',
    name: 'Jetmanus Ratisaksunthon',
    nameTH: 'นายเจตน์มนัส รติศักดิ์สุนทร',
    title: 'Computer Technical Officer',
    titleTH: 'นักวิชาการคอมพิวเตอร์',
    role: 'staff',
    department: 'Computer Technical Officers',
    departmentTH: 'บุคลากรสายปฏิบัติการ (นักวิชาการคอมพิวเตอร์)',
    email: 'jetmanus.rat@mfu.ac.th',
    phone: '0 5391 7165',
    photo: '/uploads/staff/N.Dew.png',
    bio: '',
    bioTH: '',
    expertise: [],
    expertiseTH: [],
    order: 47,
    active: true,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PAGE 4 – Administrative Officers (เจ้าหน้าที่บริหาร)
  // role: staff
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'porntip-panya',
    name: 'Porntip Panya',
    nameTH: 'นางสาวพรทิพย์ ปัญญา',
    title: 'Administrative Officer',
    titleTH: 'เจ้าหน้าที่บริหาร',
    role: 'secretary',
    department: 'Administrative Officers',
    departmentTH: 'บุคลากรสายปฏิบัติการ (เจ้าหน้าที่บริหาร)',
    email: 'porntip.pan@mfu.ac.th',
    phone: '0 5391 6745',
    photo: '/uploads/staff/P_Oi.png',
    bio: '',
    bioTH: '',
    expertise: [],
    expertiseTH: [],
    order: 48,
    active: true,
  },
  {
    id: 'rattikan-nangla',
    name: 'Rattikan Nangla',
    nameTH: 'นางสาวรัตติกาล นางแล',
    title: 'Administrative Officer',
    titleTH: 'เจ้าหน้าที่บริหาร',
    role: 'secretary',
    department: 'Administrative Officers',
    departmentTH: 'บุคลากรสายปฏิบัติการ (เจ้าหน้าที่บริหาร)',
    email: 'rattikan.nan@mfu.ac.th',
    phone: '0 5391 6742',
    photo: '/uploads/staff/P_Lek.png',
    bio: '',
    bioTH: '',
    expertise: [],
    expertiseTH: [],
    order: 49,
    active: true,
  },
  {
    id: 'pakpoom-lamprasert',
    name: 'Pakpoom Lamprasert',
    nameTH: 'นายภาคภูมิ ล้ำประเสริฐ',
    title: 'Administrative Officer',
    titleTH: 'เจ้าหน้าที่บริหาร',
    role: 'secretary',
    department: 'Administrative Officers',
    departmentTH: 'บุคลากรสายปฏิบัติการ (เจ้าหน้าที่บริหาร)',
    email: 'pakpoom.lam@mfu.ac.th',
    phone: '0 5391 6741',
    photo: '/uploads/staff/PP.png',
    bio: '',
    bioTH: '',
    expertise: [],
    expertiseTH: [],
    order: 50,
    active: true,
  },
  {
    id: 'tatchamay-wanchaisi',
    name: 'Tatchamay Wanchaisi',
    nameTH: 'นางสาวทัตต์ชไม หวานชัยสีห์',
    title: 'Administrative Officer',
    titleTH: 'เจ้าหน้าที่บริหาร',
    role: 'secretary',
    department: 'Administrative Officers',
    departmentTH: 'บุคลากรสายปฏิบัติการ (เจ้าหน้าที่บริหาร)',
    email: 'tatchamay.wah@mfu.ac.th',
    phone: '0 5391 6741',
    photo: '/uploads/staff/P_Angoon.png',
    bio: '',
    bioTH: '',
    expertise: [],
    expertiseTH: [],
    order: 51,
    active: true,
  },
  {
    id: 'sayumporn-chaichomphu',
    name: 'Sayumporn Chaichomphu',
    nameTH: 'นางสาวสยุมพร ไชยชมภู',
    title: 'Administrative Officer',
    titleTH: 'เจ้าหน้าที่บริหาร',
    role: 'secretary',
    department: 'Administrative Officers',
    departmentTH: 'บุคลากรสายปฏิบัติการ (เจ้าหน้าที่บริหาร)',
    email: 'sayumporn.cha@mfu.ac.th',
    phone: '0 5391 6742',
    photo: '/uploads/staff/P_Nim.png',
    bio: '',
    bioTH: '',
    expertise: [],
    expertiseTH: [],
    order: 52,
    active: true,
  },
];

export default scrapedStaff;
